### ISSUE TITLE
Not handling correctly `request.url` when inject an invalid URL

### ISSUE THREAD

**Issue by rtrys** [pinojs/pino-std-serializers#28]
We recently had a problem with pino in hapi, because hapi is unable to create the `request.url` object when the URL is invalid, see this [gist](https://gist.github.com/rtrys/d7a4b3ad586654f129eea9ee64b9a1fd)

**Comment by jsumners** [comment]
Please state what the problem is.

**Comment by rtrys** [comment]
the node process crash when you send or inject an invalid URL, and I expect and 404

**Comment by jsumners** [comment]
Is there an error message? What is it?

**Comment by rtrys** [comment]
yep, here are the log traces
```bash
TypeError [ERR_INVALID_URL]: Invalid URL: http://:80/(a%7Cb).loclhost:80a/
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at Request._parseUrl (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/@hapi/hapi/lib/request.js:180:25)
    at Request.get url [as url] (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/@hapi/hapi/lib/request.js:114:21)
    at Object.reqSerializer [as req] (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/pino-std-serializers/lib/req.js:66:20)
    at asChindings (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/pino/lib/tools.js:173:50)
    at Pino.child (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/pino/lib/proto.js:120:28)
    at /Users/huortiz/dev/plat/consumer-apps-ol/node_modules/hapi-pino/index.js:93:29
    at exports.Manager.execute (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
    at Request._invoke (/Users/huortiz/dev/plat/consumer-apps-ol/node_modules/@hapi/hapi/lib/request.js:391:55) {
```

I doing PR to propose to use `request.path` instead of `request.url.path` to avoid this error
